apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboardback-deployment
  labels:
    app: dashboardback
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dashboardback
  template:
    metadata:
      labels:
        app: dashboardback
    spec:
      containers:
      - name: dashboardback
        image: anisossss/admin-dashboard-CI-CD-integration
        ports:
        - containerPort: 80
